import {
  siJavascript,
  siTypescript,
  siPython,
  siOpenjdk,
  siC,
  siCplusplus,
  siPhp,
  siGo,
  siRust,
  siKotlin,
  siSwift,
  siRuby,
  siScala,
  siPerl,
  siElixir,
  siHaskell,
  siDart,
  siSolidity,
  siHtml5,
  siCss,
  siSass,
  siLess,
  siReact,
  siVuedotjs,
  siAngular,
  siSvelte,
  siSolid,
  siNextdotjs,
  siNuxt,
  siGatsby,
  siRemix,
  siAstro,
  siNodedotjs,
  siDeno,
  siBun,
  siExpress,
  siNestjs,
  siFastapi,
  siDjango,
  siFlask,
  siSpring,
  siDotnet,
  siLaravel,
  siSymfony,
  siRubyonrails,
  siTailwindcss,
  siBootstrap,
  siJquery,
  siGraphql,
  siPrisma,
  siSequelize,
  siMongoose,
  siRedux,
  siWebpack,
  siVite,
  siBabel,
  siEslint,
  siPrettier,
  siJest,
  siCypress,
  siSelenium,
  siStorybook,
  siDocker,
  siKubernetes,
  siJenkins,
  siTerraform,
  siAnsible,
  siGooglecloud,
  siGit,
  siGithub,
  siGitlab,
  siBitbucket,
  siJira,
  siConfluence,
  siNetlify,
  siVercel,
  siFirebase,
  siSupabase,
  siLinux,
  siGnubash,
  siNginx,
  siApache,
  siMysql,
  siPostgresql,
  siMongodb,
  siRedis,
  siSqlite,
  siMariadb,
  siApachecassandra,
  siApachekafka,
  siElasticsearch,
  siRabbitmq,
  siNeo4j,
  siInfluxdb,
  siCockroachlabs,
  siSnowflake,
  siApacheairflow,
  siNumpy,
  siPandas,
  siTensorflow,
  siPytorch,
  siFlutter,
  siAndroid,
  siAndroidstudio,
  siApple,
  siXcode,
  siUnity,
  siUnrealengine,
  siGodotengine,
  siWebassembly,
  siWordpress,
  siShopify,
  siStripe,
  siFigma,
  siBlender,
  siSketch,
  siNpm,
  siYarn,
  siPnpm,
  siPostman,
  siSwagger,
  siGrafana,
  siPrometheus,
  siKibana,
  siWebstorm,
  siIntellijidea,
  siNotion,
  siTrello,
  siAsana,
  siAntdesign,
  siChakraui,
} from 'simple-icons'

/** The 40 most in-demand technologies across languages, frontend/backend frameworks,
 * cloud/DevOps and databases — the "pick from a list" set for "Mi perfil de búsqueda"
 * (lib/settings.ts) and shown here in a sensible display order. A handful (C#, SQL) genuinely
 * have no logo in simple-icons — those brands don't license their mark for redistribution,
 * so simple-icons excludes them; they still show up by name everywhere, just without an
 * icon next to them. Java uses the OpenJDK logo as a stand-in for the same reason (Oracle
 * doesn't license the coffee-cup mark). */
export const TOP_TECHNOLOGIES = [
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C#',
  'C++',
  'PHP',
  'Go',
  'Rust',
  'Kotlin',
  'Swift',
  'Ruby',
  'SQL',
  'HTML5',
  'CSS',
  'React',
  'Vue.js',
  'Angular',
  'Next.js',
  'Node.js',
  'Express',
  'Django',
  'Flask',
  'Spring',
  '.NET',
  'Laravel',
  'Tailwind CSS',
  'jQuery',
  'GraphQL',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'Google Cloud',
  'Git',
  'GitHub',
  'Linux',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
] as const

interface Logo {
  path: string
  hex: string
}

/** Every recognized name (and common alternate spellings/casings) maps to the same
 * simple-icons brand data — case-insensitive lookup via getTechLogo below. This covers a
 * lot more than TOP_TECHNOLOGIES on purpose: skills are free-typed text (SkillsForm), so
 * someone writing "Redis", "Figma" or "Terraform" should still get an icon next to it, not
 * just the 40 tags suggested in "Mi perfil de búsqueda". */
const ALIASES: Record<string, Logo> = {
  javascript: siJavascript,
  js: siJavascript,
  typescript: siTypescript,
  ts: siTypescript,
  python: siPython,
  java: siOpenjdk,
  c: siC,
  'lenguaje c': siC,
  'c++': siCplusplus,
  cplusplus: siCplusplus,
  php: siPhp,
  go: siGo,
  golang: siGo,
  rust: siRust,
  kotlin: siKotlin,
  swift: siSwift,
  ruby: siRuby,
  scala: siScala,
  perl: siPerl,
  elixir: siElixir,
  haskell: siHaskell,
  dart: siDart,
  solidity: siSolidity,
  html: siHtml5,
  html5: siHtml5,
  css: siCss,
  css3: siCss,
  sass: siSass,
  scss: siSass,
  less: siLess,
  react: siReact,
  'react.js': siReact,
  reactjs: siReact,
  vue: siVuedotjs,
  'vue.js': siVuedotjs,
  vuejs: siVuedotjs,
  angular: siAngular,
  svelte: siSvelte,
  sveltekit: siSvelte,
  solidjs: siSolid,
  'solid.js': siSolid,
  'next.js': siNextdotjs,
  nextjs: siNextdotjs,
  next: siNextdotjs,
  nuxt: siNuxt,
  'nuxt.js': siNuxt,
  gatsby: siGatsby,
  remix: siRemix,
  astro: siAstro,
  'node.js': siNodedotjs,
  nodejs: siNodedotjs,
  node: siNodedotjs,
  deno: siDeno,
  bun: siBun,
  express: siExpress,
  'express.js': siExpress,
  expressjs: siExpress,
  nestjs: siNestjs,
  'nest.js': siNestjs,
  fastapi: siFastapi,
  django: siDjango,
  flask: siFlask,
  spring: siSpring,
  'spring boot': siSpring,
  springboot: siSpring,
  '.net': siDotnet,
  dotnet: siDotnet,
  '.net core': siDotnet,
  'asp.net': siDotnet,
  laravel: siLaravel,
  symfony: siSymfony,
  'ruby on rails': siRubyonrails,
  rails: siRubyonrails,
  'tailwind css': siTailwindcss,
  tailwindcss: siTailwindcss,
  tailwind: siTailwindcss,
  bootstrap: siBootstrap,
  jquery: siJquery,
  graphql: siGraphql,
  prisma: siPrisma,
  sequelize: siSequelize,
  mongoose: siMongoose,
  redux: siRedux,
  webpack: siWebpack,
  vite: siVite,
  babel: siBabel,
  eslint: siEslint,
  prettier: siPrettier,
  jest: siJest,
  cypress: siCypress,
  selenium: siSelenium,
  storybook: siStorybook,
  docker: siDocker,
  kubernetes: siKubernetes,
  k8s: siKubernetes,
  jenkins: siJenkins,
  terraform: siTerraform,
  ansible: siAnsible,
  'google cloud': siGooglecloud,
  googlecloud: siGooglecloud,
  gcp: siGooglecloud,
  git: siGit,
  github: siGithub,
  gitlab: siGitlab,
  bitbucket: siBitbucket,
  jira: siJira,
  confluence: siConfluence,
  netlify: siNetlify,
  vercel: siVercel,
  firebase: siFirebase,
  supabase: siSupabase,
  linux: siLinux,
  bash: siGnubash,
  shell: siGnubash,
  'shell scripting': siGnubash,
  nginx: siNginx,
  apache: siApache,
  mysql: siMysql,
  postgresql: siPostgresql,
  postgres: siPostgresql,
  mongodb: siMongodb,
  mongo: siMongodb,
  redis: siRedis,
  sqlite: siSqlite,
  mariadb: siMariadb,
  cassandra: siApachecassandra,
  kafka: siApachekafka,
  'apache kafka': siApachekafka,
  elasticsearch: siElasticsearch,
  rabbitmq: siRabbitmq,
  neo4j: siNeo4j,
  influxdb: siInfluxdb,
  cockroachdb: siCockroachlabs,
  snowflake: siSnowflake,
  airflow: siApacheairflow,
  'apache airflow': siApacheairflow,
  numpy: siNumpy,
  pandas: siPandas,
  tensorflow: siTensorflow,
  pytorch: siPytorch,
  flutter: siFlutter,
  android: siAndroid,
  'android studio': siAndroidstudio,
  ios: siApple,
  apple: siApple,
  xcode: siXcode,
  unity: siUnity,
  'unreal engine': siUnrealengine,
  unrealengine: siUnrealengine,
  godot: siGodotengine,
  webassembly: siWebassembly,
  wasm: siWebassembly,
  wordpress: siWordpress,
  shopify: siShopify,
  stripe: siStripe,
  figma: siFigma,
  blender: siBlender,
  sketch: siSketch,
  npm: siNpm,
  yarn: siYarn,
  pnpm: siPnpm,
  postman: siPostman,
  swagger: siSwagger,
  openapi: siSwagger,
  grafana: siGrafana,
  prometheus: siPrometheus,
  kibana: siKibana,
  webstorm: siWebstorm,
  intellij: siIntellijidea,
  'intellij idea': siIntellijidea,
  notion: siNotion,
  trello: siTrello,
  asana: siAsana,
  'ant design': siAntdesign,
  antdesign: siAntdesign,
  chakra: siChakraui,
  'chakra ui': siChakraui,
}

/** Looks up a brand logo by technology name — case-insensitive, tolerant of the common
 * ways people actually type these (".NET" vs "dotnet", "Node" vs "Node.js"…). Returns
 * null for anything not recognized (a custom skill someone typed in, or one of the
 * handful of brands with no redistributable logo) — callers should render nothing in
 * that case, not a generic placeholder icon. */
export function getTechLogo(name: string): Logo | null {
  return ALIASES[name.trim().toLowerCase()] ?? null
}
